Repository DeepLink-org/DIOPI, pull requests merged in 2024-08, with the labels that each got.

#1315 [DIOPI] fix adamw test when amsgrad is False
  diopi_test/python/configs/diopi_configs.py
  impl/camb/device_configs.py
  impl/camb/functions/adam.cpp
  impl/torch/functions/functions.cpp
Labels: diopi_test

#1335 feat: add a new diopiError_t enum to fallback to cpu
  proto/include/diopi/diopirt.h
Labels: feature

#1341 build(droplet): add DEVICEIMPL as imported library
  impl/droplet/CMakeLists.txt
  impl/droplet/test/CMakeLists.txt
Labels: bug
